org: ${env:SLS_ORG}
service: papa-johns-empleados-api

provider:
  name: aws
  runtime: python3.12
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  memorySize: 1024
  timeout: 29
  iam:
    role: arn:aws:iam::${aws:accountId}:role/LabRole
  environment:
    ORDERS_TABLE: papa-johns-order-service-orders-${self:provider.stage}
    SQS_COCINA_URL: https://sqs.${aws:region}.amazonaws.com/${aws:accountId}/papa-johns-order-service-cocina-queue-${self:provider.stage}
    SQS_EMPAQUE_URL: https://sqs.${aws:region}.amazonaws.com/${aws:accountId}/papa-johns-order-service-empaque-queue-${self:provider.stage}
    SQS_DESPACHO_URL: https://sqs.${aws:region}.amazonaws.com/${aws:accountId}/papa-johns-order-service-despacho-queue-${self:provider.stage}

functions:
  getTasksCocina:
    handler: src/handlers/get_tasks_cocina.handler
    events:
      - http:
          path: /tasks/cocina
          method: get
          cors: true

  getTasksEmpaque:
    handler: src/handlers/get_tasks_empaque.handler
    events:
      - http:
          path: /tasks/empaque
          method: get
          cors: true

  getTasksDespacho:
    handler: src/handlers/get_tasks_despacho.handler
    events:
      - http:
          path: /tasks/despacho
          method: get
          cors: true

  updateOrderStatus:
    handler: src/handlers/update_order_status.handler
    events:
      - http:
          path: /tenants/{tenantId}/orders/{id}/status
          method: patch
          cors: true